### ISSUE TITLE
Triple store port

### ISSUE THREAD

**Issue by lmarcoruiz** [kmi-dockerfiles/docker-sesame#1]
Current Docker version triple store is running on port 3030 rather than 8080 as it is mentioned in the docker tutorial:
http://192.168.59.103:3030

**Comment by cpedrinaci** [comment]
I'm not sure I understand this. The README shows that the port can be established once you launch it. See '-p' option

**Comment by lmarcoruiz** [comment]
Hi,
It was a reference to the need of update for the wiki on https://github.com/kmi-dockerfiles/docker-iserve that mentions  "On port 9090 you should have access to the underlying Sesame store". It took me some time to realize that the triple store was not in that port because it was Fuseki listening on 3030
I also had trouble accessing the Fuseki instance running on iServe Docker since it requires user and password. However, in the log files, only the user and password for iServe are provided. Is this information available elsewhere?

Thanks,
Luis

**Comment by cpedrinaci** [comment]
So this does not relate to this project. I'm closing this.

Configuring Fuseki can be done in its own docker container (stain/jena-fuseki) 
See for instance the configuration params in https://github.com/kmi-dockerfiles/docker-iserve/blob/master/docker-compose.yml
